#!/usr/bin/env bash
#Bash script to change localhost to 127.0.0.2 and facebook.com to 8.8.8.8.
sudo cp /etc/hosts /etc/hosts.bak
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
